import { initComponents } from './components.js';
import { getProductsByType, getProductMainImage, subscribeToProductChanges } from '../services/productService.js';
import { initReservationModal, openReservationModal } from './reservationModal.js';
import { formatPrice, escapeHTML } from './utils.js';

const CONDITION_LABELS={new:'Novo',worn:'Nošeno',very_good:'Vrlo dobro',damaged:'Oštećeno'};
let products=[];

function card(product){const available=product.stock>0,gender=({men:'Muški',women:'Ženski',unisex:'Unisex'})[product.genderCategory]||product.genderCategory;return `<article class="product-card other-card reveal" data-product-id="${escapeHTML(product.id)}"><div class="card-media"><span class="badge">${product.productType==='sneaker'?'TENISICE':'DUKS'}</span><a href="product.html?id=${escapeHTML(product.id)}"><img src="${escapeHTML(getProductMainImage(product))}" alt="${escapeHTML(product.name)}" loading="lazy"></a></div><div class="card-content"><p class="card-club"><span>${escapeHTML(product.brand)}</span><span class="condition-chip">${CONDITION_LABELS[product.condition]||''}</span></p><a href="product.html?id=${escapeHTML(product.id)}"><h3>${escapeHTML(product.name)}</h3></a><dl class="product-meta"><div><dt>Veličina</dt><dd>${escapeHTML(product.sizes.join(', '))}</dd></div><div><dt>Boja</dt><dd>${escapeHTML(product.color)}</dd></div><div><dt>Kategorija</dt><dd>${escapeHTML(gender)}</dd></div>${product.productType==='sneaker'&&product.hasOriginalBox?'<div><dt>Kutija</dt><dd>Da</dd></div>':''}</dl><div class="stock-status ${available?'in-stock':'sold-out'}"><span></span>${available?'Na stanju':'Rasprodano'}</div><div class="card-footer"><div class="price-wrap"><strong>${formatPrice(product.price)}</strong></div><button class="button button-primary reserve-button" type="button" data-reserve="${escapeHTML(product.id)}" ${available?'':'disabled'}>Rezerviraj</button></div></div></article>`;}

function render(){const form=document.querySelector('[data-other-controls]'),data=new FormData(form),query=String(data.get('query')||'').toLocaleLowerCase('hr'),category=data.get('category'),size=data.get('size'),price=data.get('price'),condition=data.get('condition'),brand=data.get('brand'),color=data.get('color'),sort=data.get('sort');let filtered=products.filter((product)=>(category==='all'||product.productType===category)&&(size==='all'||product.sizes.includes(size))&&(condition==='all'||product.condition===condition)&&(brand==='all'||product.brand===brand)&&(color==='all'||product.color===color)&&(!query||`${product.name} ${product.brand} ${product.color} ${product.description}`.toLocaleLowerCase('hr').includes(query))&&(price==='all'||price==='under50'&&product.price<50||price==='50to100'&&product.price>=50&&product.price<=100||price==='over100'&&product.price>100));filtered=[...filtered].sort((a,b)=>sort==='price-asc'?a.price-b.price:sort==='price-desc'?b.price-a.price:sort==='name'?a.name.localeCompare(b.name,'hr'):new Date(b.createdAt)-new Date(a.createdAt));for(const[type,selector]of[['sneaker','sneaker'],['hoodie','hoodie']]){const items=filtered.filter((product)=>product.productType===type),section=document.querySelector(`[data-${selector}-section]`);section.hidden=category!=='all'&&category!==type;document.querySelector(`[data-${selector}-count]`).textContent=`${items.length} proizvoda`;document.querySelector(`[data-${selector}-grid]`).innerHTML=items.length?items.map(card).join(''):'<div class="empty-state grid-empty"><h2>Nema rezultata</h2><p>Promijenite pretragu ili filtre.</p></div>';}}

async function init(){await initComponents();initReservationModal();products=await getProductsByType(['sneaker','hoodie']);const form=document.querySelector('[data-other-controls]');for(const[name,values]of[['size',[...new Set(products.flatMap((product)=>product.sizes))]],['brand',[...new Set(products.map((product)=>product.brand).filter(Boolean))]],['color',[...new Set(products.map((product)=>product.color).filter(Boolean))]]]){const select=form.elements[name];values.sort((a,b)=>String(a).localeCompare(String(b),'hr',{numeric:true})).forEach((value)=>select.insertAdjacentHTML('beforeend',`<option value="${escapeHTML(value)}">${escapeHTML(value)}</option>`));}form.addEventListener('input',render);form.addEventListener('change',render);document.addEventListener('click',async(event)=>{const button=event.target.closest('[data-reserve]');if(button)await openReservationModal(button.dataset.reserve);});render();await subscribeToProductChanges((fresh)=>{products=fresh;render();},['sneaker','hoodie']);}
init().catch((error)=>{document.querySelector('[data-sneaker-grid]').innerHTML=`<div class="empty-state grid-empty"><h2>Proizvodi nisu dostupni</h2><p>${escapeHTML(error.message)}</p></div>`;});
