import { readStorage, writeStorage } from '../js/storage.js';
import { getSupabaseClient, isSupabaseConfigured, reportSupabaseError, throwIfSupabaseError } from './supabaseClient.js';

const KEY='dreshub.admin.notes';
const META={service:'noteService',table:'notes'};

function fromDatabase(row,relatedProductIds=[]){const legacyProductId=row.linked_type==='product'?row.linked_id:null,productIds=[...new Set([...relatedProductIds,legacyProductId].filter(Boolean).map(String))];return{id:row.id,title:row.title,description:row.content||'',type:row.type,amount:row.amount,dueDate:row.deadline,priority:row.priority,status:row.status,pinned:Boolean(row.is_pinned),tags:row.tags||[],productIds,productId:productIds[0]||null,orderId:row.linked_type==='purchase_order'?row.linked_id:null,linkedType:row.linked_type,linkedId:row.linked_id,createdAt:row.created_at,updatedAt:row.updated_at};}
function toDatabase(note){const productIds=(note.productIds||[note.productId]).filter(Boolean),linkedType=note.orderId?'purchase_order':productIds.length?'product':null,linkedId=note.orderId||productIds[0]||null;return{title:note.title,content:note.description||'',type:note.type,amount:note.amount??null,deadline:note.dueDate||null,priority:note.priority,status:note.status,is_pinned:Boolean(note.pinned),linked_type:linkedType,linked_id:linkedId,tags:note.tags||[]};}
function localNotes(){return readStorage(KEY,[]);}

async function syncNoteProducts(client,noteId,productIds){const desired=[...new Set((productIds||[]).filter(Boolean).map(String))],current=await client.from('note_products').select('product_id').eq('note_id',noteId);throwIfSupabaseError(current.error,{service:'noteService',table:'note_products',operation:'dohvat postojećih veza',columns:['note_id','product_id']});const existing=(current.data||[]).map((row)=>String(row.product_id)),toAdd=desired.filter((id)=>!existing.includes(id)),toRemove=existing.filter((id)=>!desired.includes(id));if(toAdd.length){const inserted=await client.from('note_products').insert(toAdd.map((productId)=>({note_id:noteId,product_id:productId})));throwIfSupabaseError(inserted.error,{service:'noteService',table:'note_products',operation:'spremanje povezanih dresova',columns:['note_id','product_id']});}if(toRemove.length){const removal=await client.from('note_products').delete().eq('note_id',noteId).in('product_id',toRemove);throwIfSupabaseError(removal.error,{service:'noteService',table:'note_products',operation:'uklanjanje veza dresova',columns:['note_id','product_id']});}}

export async function getNotes(){const client=await getSupabaseClient();if(client){const notes=await client.from('notes').select('*');if(notes.error){reportSupabaseError(notes.error,{...META,operation:'dohvat bilješki',columns:['*']});return[];}const links=await client.from('note_products').select('note_id,product_id');if(links.error)reportSupabaseError(links.error,{service:'noteService',table:'note_products',operation:'dohvat povezanih dresova',columns:['note_id','product_id']});const byNote=new Map();for(const link of links.data||[]){const key=String(link.note_id),ids=byNote.get(key)||[];ids.push(link.product_id);byNote.set(key,ids);}return(notes.data||[]).map((row)=>fromDatabase(row,byNote.get(String(row.id))||[])).sort((a,b)=>Number(b.pinned)-Number(a.pinned)||new Date(b.createdAt||0)-new Date(a.createdAt||0));}return isSupabaseConfigured()?[]:localNotes();}
export async function getNoteById(noteId){return(await getNotes()).find((note)=>String(note.id)===String(noteId))??null;}
export async function createNote(noteData){const client=await getSupabaseClient();if(client){const payload=toDatabase(noteData),result=await client.from('notes').insert(payload).select().single();throwIfSupabaseError(result.error,{...META,operation:'stvaranje bilješke',columns:Object.keys(payload)});await syncNoteProducts(client,result.data.id,noteData.productIds||[]);return fromDatabase(result.data,noteData.productIds||[]);}if(isSupabaseConfigured())throw new Error('Supabase bilješke trenutačno nisu dostupne.');const note={id:Date.now(),createdAt:new Date().toISOString(),pinned:false,status:'Aktivna',productIds:[],...noteData};writeStorage(KEY,[note,...localNotes()]);return note;}
export async function updateNote(noteId,noteData){const client=await getSupabaseClient();if(client){const current=await getNoteById(noteId);if(!current)throw new Error(`Bilješka ${noteId} nije pronađena.`);const merged={...current,...noteData},payload=toDatabase(merged),result=await client.from('notes').update(payload).eq('id',String(noteId)).select().single();throwIfSupabaseError(result.error,{...META,operation:'ažuriranje bilješke',columns:Object.keys(payload)});await syncNoteProducts(client,noteId,merged.productIds||[]);return fromDatabase(result.data,merged.productIds||[]);}if(isSupabaseConfigured())throw new Error('Supabase bilješke trenutačno nisu dostupne.');const notes=localNotes(),note=notes.find((item)=>String(item.id)===String(noteId));if(!note)return null;Object.assign(note,noteData);writeStorage(KEY,notes);return note;}
export async function deleteNote(noteId){const client=await getSupabaseClient();if(client){const{error}=await client.from('notes').delete().eq('id',String(noteId));throwIfSupabaseError(error,{...META,operation:'brisanje bilješke',columns:['id']});return;}if(isSupabaseConfigured())throw new Error('Supabase bilješke trenutačno nisu dostupne.');writeStorage(KEY,localNotes().filter((item)=>String(item.id)!==String(noteId)));}
export async function archiveNote(noteId){return updateNote(noteId,{status:'Arhivirana'});}
export async function pinNote(noteId){return updateNote(noteId,{pinned:true});}
export async function unpinNote(noteId){return updateNote(noteId,{pinned:false});}
export async function completeNote(noteId){return updateNote(noteId,{status:'Završena'});}
