import { readStorage, writeStorage } from '../js/storage.js';
import { getAllProducts, getProductById, createProduct, updateProduct, incrementProductQuantity } from './productService.js';
import { createTransaction } from './transactionService.js';
import { createChangeHistoryEntry } from './changeHistoryService.js';
import { getSupabaseClient, isSupabaseConfigured, reportSupabaseError, throwIfSupabaseError } from './supabaseClient.js';

const KEY = 'dreshub.admin.orders';

/** @param {Object} item DB stavka. @returns {Object} UI stavka. */
function itemFromDatabase(item){return{id:item.id,orderId:item.purchase_order_id,productId:item.product_id,isNewProduct:Boolean(item.is_new_product),name:item.name,club:item.club,player:item.player,type:item.category,category:item.category,version:item.version,size:item.size,quantity:Number(item.quantity||0),costPrice:Number(item.buy_price||0),price:Number(item.sell_price||0),note:item.note||'',createdAt:item.created_at};}
/** @param {Object} item UI stavka. @returns {Object} DB stavka. */
function itemToDatabase(item){return{product_id:item.productId||null,is_new_product:Boolean(item.isNewProduct||!item.productId),name:item.name,club:item.club||null,player:item.player||null,category:item.type||item.category||null,version:item.version||null,size:item.size||null,quantity:Number(item.quantity||0),buy_price:Number(item.costPrice||0),sell_price:Number(item.price||0),note:item.note||''};}
/** @param {Object} order UI narudžba. @returns {Object} DB narudžba. */
function orderToDatabase(order){const items=order.items||[],totalItems=items.reduce((sum,item)=>sum+Number(item.quantity||0),0),totalCost=items.reduce((sum,item)=>sum+Number(item.quantity||0)*Number(item.costPrice||0),0),sales=items.reduce((sum,item)=>sum+Number(item.quantity||0)*Number(item.price||0),0);return{title:order.title,supplier:order.supplier||null,status:order.status||'open',total_items:Number(order.totalItems??totalItems),total_cost:Number(order.totalCost??totalCost),estimated_sales_value:Number(order.estimatedSalesValue??sales),estimated_profit:Number(order.estimatedProfit??(sales-totalCost)),note:order.note||'',...(order.finalizedAt?{finalized_at:order.finalizedAt}:{}),...(order.cancelledAt?{cancelled_at:order.cancelledAt}:{})};}

/** @returns {Promise<Array<Object>>} Sve narudžbe nabave. */
export async function getPurchaseOrders() {
  const client=await getSupabaseClient();if(client){const{data,error}=await client.from('purchase_orders').select('*, purchase_order_items(*)');if(!error)return(data??[]).map((order)=>({...order,totalItems:order.total_items,totalCost:order.total_cost,estimatedSalesValue:order.estimated_sales_value,estimatedProfit:order.estimated_profit,createdAt:order.created_at,finalizedAt:order.finalized_at,cancelledAt:order.cancelled_at,closedAt:order.finalized_at,items:(order.purchase_order_items||[]).map(itemFromDatabase)})).sort((a,b)=>new Date(b.createdAt||0)-new Date(a.createdAt||0));reportSupabaseError(error,{service:'purchaseOrderService',table:'purchase_orders + purchase_order_items',operation:'dohvat narudžbi',columns:['*']});return[];}return isSupabaseConfigured()?[]:readStorage(KEY,[]);
}
/** @param {number|string} orderId ID. @returns {Promise<Object|null>} */
export async function getPurchaseOrderById(orderId){return(await getPurchaseOrders()).find((order)=>order.id===Number(orderId))??null;}

/** @param {Object} orderData Podaci narudžbe. @returns {Promise<Object>} */
export async function createPurchaseOrder(orderData){const client=await getSupabaseClient();if(client){const{items=[],...order}=orderData;const payload=orderToDatabase({...order,items,status:'open'}),{data,error}=await client.from('purchase_orders').insert(payload).select().single();throwIfSupabaseError(error,{service:'purchaseOrderService',table:'purchase_orders',operation:'stvaranje narudžbe',columns:Object.keys(payload)});for(const item of items)await addItemToPurchaseOrder(data.id,item);return getPurchaseOrderById(data.id);}if(isSupabaseConfigured())throw new Error('Supabase narudžbe trenutačno nisu dostupne.');const record={id:Date.now(),status:'open',createdAt:new Date().toISOString(),items:[],...orderData};writeStorage(KEY,[record,...readStorage(KEY,[])]);await createChangeHistoryEntry({category:'orders',description:`Otvorena narudžba: ${record.title}`,oldValue:null,newValue:record});return record;}

/** @param {number|string} orderId ID. @param {Object} orderData Izmjene. @returns {Promise<Object|null>} */
export async function updatePurchaseOrder(orderId,orderData){const client=await getSupabaseClient();if(client){const current=await getPurchaseOrderById(orderId);if(!current)return null;const{items,...order}=orderData,payload=orderToDatabase({...current,...order,items:items||current.items}),{data,error}=await client.from('purchase_orders').update(payload).eq('id',orderId).eq('status','open').select().single();throwIfSupabaseError(error,{service:'purchaseOrderService',table:'purchase_orders',operation:'ažuriranje narudžbe',columns:Object.keys(payload)});if(items){const removal=await client.from('purchase_order_items').delete().eq('purchase_order_id',orderId);throwIfSupabaseError(removal.error,{service:'purchaseOrderService',table:'purchase_order_items',operation:'čišćenje stavki narudžbe',columns:['purchase_order_id']});for(const item of items){const{id,...itemPayload}=item;await addItemToPurchaseOrder(orderId,itemPayload);}}return{...current,...data,...orderData,createdAt:data.created_at,finalizedAt:data.finalized_at,cancelledAt:data.cancelled_at,closedAt:data.finalized_at};}if(isSupabaseConfigured())throw new Error('Supabase narudžbe trenutačno nisu dostupne.');const orders=readStorage(KEY,[]),order=orders.find((item)=>item.id===Number(orderId)&&item.status==='open');if(!order)return null;Object.assign(order,orderData,{items:orderData.items||order.items});writeStorage(KEY,orders);return order;}

/** @param {number|string} orderId ID. @returns {Promise<Object|null>} */
export async function cancelPurchaseOrder(orderId){return updatePurchaseOrder(orderId,{status:'cancelled',cancelledAt:new Date().toISOString()});}

/**
 * Zaključuje narudžbu i atomizira poslovne posljedice na razini servisa.
 * @param {number|string} orderId ID narudžbe.
 * @returns {Promise<Object|null>} Zaključena narudžba.
 */
export async function finalizePurchaseOrder(orderId){const order=await getPurchaseOrderById(orderId);if(!order||order.status!=='open')return null;for(const item of order.items){if(item.productId){await incrementProductQuantity(item.productId,Number(item.quantity));const product=await getProductById(item.productId);if(product)await updateProduct(product.id,{...product,costPrice:Number(item.costPrice),price:Number(item.price)});}else await createProduct({name:item.name,club:item.club||'Novi proizvod',player:item.player||'Bez tiska',type:item.type||item.category||'club',version:item.version||'Fan Version',sizes:[item.size||'M'],costPrice:Number(item.costPrice),price:Number(item.price),oldPrice:null,stock:Number(item.quantity),badge:'NOVO',description:item.note||'Proizvod iz narudžbe.',images:[]});}const cost=order.items.reduce((sum,item)=>sum+Number(item.quantity)*Number(item.costPrice),0);await createTransaction({type:'Trošak',amount:-cost,description:`Zaključena nabava: ${order.title}`,sourceType:'purchase_order',sourceId:order.id,date:new Date().toISOString()});const client=await getSupabaseClient();let closed;if(client){const finalizedAt=new Date().toISOString(),{data,error}=await client.from('purchase_orders').update({status:'closed',finalized_at:finalizedAt}).eq('id',orderId).select().single();throwIfSupabaseError(error,{service:'purchaseOrderService',table:'purchase_orders',operation:'zaključivanje narudžbe',columns:['status','finalized_at']});closed={...order,...data,status:'closed',finalizedAt,closedAt:finalizedAt};}else{if(isSupabaseConfigured())throw new Error('Supabase narudžbe trenutačno nisu dostupne.');const orders=readStorage(KEY,[]);closed=orders.find((item)=>item.id===Number(orderId));closed.status='closed';closed.closedAt=new Date().toISOString();writeStorage(KEY,orders);}await createChangeHistoryEntry({category:'orders',entityId:order.id,changeType:'finalize',description:`Zaključena narudžba: ${order.title}`,oldValue:'open',newValue:'closed'});return closed;}

/** @param {number|string} orderId ID. @returns {Promise<Object|null>} Nova otvorena kopija. */
export async function copyPurchaseOrder(orderId){const order=await getPurchaseOrderById(orderId);return order?createPurchaseOrder({title:`Kopija - ${order.title}`,note:order.note||'',items:order.items.map(({id,...item})=>item)}):null;}

/** @param {number|string} orderId ID narudžbe. @param {Object} itemData Stavka. @returns {Promise<Object>} */
export async function addItemToPurchaseOrder(orderId,itemData){const client=await getSupabaseClient();if(client){const payload={...itemToDatabase(itemData),purchase_order_id:orderId},{data,error}=await client.from('purchase_order_items').insert(payload).select().single();throwIfSupabaseError(error,{service:'purchaseOrderService',table:'purchase_order_items',operation:'dodavanje stavke narudžbe',columns:Object.keys(payload)});return itemFromDatabase(data);}if(isSupabaseConfigured())throw new Error('Supabase stavke narudžbe trenutačno nisu dostupne.');const orders=readStorage(KEY,[]),order=orders.find((item)=>item.id===Number(orderId)&&item.status==='open');if(!order)throw new Error('Otvorena narudžba nije pronađena.');const item={id:Date.now()+Math.random(),...itemData};order.items.push(item);writeStorage(KEY,orders);return item;}

/** @param {number|string} itemId ID stavke. @param {Object} itemData Izmjene. @returns {Promise<Object|null>} */
export async function updatePurchaseOrderItem(itemId,itemData){const client=await getSupabaseClient();if(client){const currentResult=await client.from('purchase_order_items').select('*').eq('id',itemId).single();throwIfSupabaseError(currentResult.error,{service:'purchaseOrderService',table:'purchase_order_items',operation:'dohvat stavke narudžbe',columns:['id']});const payload=itemToDatabase({...itemFromDatabase(currentResult.data),...itemData}),{data,error}=await client.from('purchase_order_items').update(payload).eq('id',itemId).select().single();throwIfSupabaseError(error,{service:'purchaseOrderService',table:'purchase_order_items',operation:'ažuriranje stavke narudžbe',columns:Object.keys(payload)});return itemFromDatabase(data);}if(isSupabaseConfigured())throw new Error('Supabase stavke narudžbe trenutačno nisu dostupne.');const orders=readStorage(KEY,[]);for(const order of orders){const item=order.items.find((entry)=>entry.id===Number(itemId));if(item&&order.status==='open'){Object.assign(item,itemData);writeStorage(KEY,orders);return item;}}return null;}

/** @param {number|string} itemId ID stavke. @returns {Promise<void>} */
export async function removePurchaseOrderItem(itemId){const client=await getSupabaseClient();if(client){const{error}=await client.from('purchase_order_items').delete().eq('id',itemId);throwIfSupabaseError(error,{service:'purchaseOrderService',table:'purchase_order_items',operation:'brisanje stavke',columns:['id']});return;}if(isSupabaseConfigured())throw new Error('Supabase stavke narudžbe trenutačno nisu dostupne.');const orders=readStorage(KEY,[]);orders.forEach((order)=>{if(order.status==='open')order.items=order.items.filter((item)=>item.id!==Number(itemId));});writeStorage(KEY,orders);}
